# Generated by Django 4.1 on 2024-08-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=400)),
                ('des', models.TextField(max_length=600)),
                ('price', models.TextField(max_length=600)),
                ('sales_price', models.TextField(max_length=600)),
                ('stock', models.CharField(max_length=400)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
