# Generated by Django 4.1 on 2024-08-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cate',
            field=models.CharField(blank=True, choices=[('Vegitables', 'Vegitbales'), ('Fruit', 'Fruit'), ('Groccery', 'Groccery')], max_length=20),
        ),
    ]
