# Generated by Django 4.1 on 2024-08-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_product_cartitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='cate',
            field=models.CharField(blank=True, choices=[('Vegitables', 'Vegitbales'), ('Fruit', 'Fruit'), ('Electronics', 'Electronics'), ('Groccery', 'Groccery')], max_length=20),
        ),
    ]
