# Generated by Django 4.1 on 2024-08-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_item_cartitem_product_alter_product_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cate',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Groccery', 'Groccery'), ('Fruit', 'Fruit'), ('Vegitables', 'Vegitbales')], max_length=20),
        ),
    ]
